spring:
  application: 
    name: test-client
    
    
server:
  port: 3333
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
  instance:
    leaseRenewalIntervalInSeconds: 5 #reduce the lease renewal interval to speed up regisgration **dev only**
    